steps:
  - name: Provision Jekyll test site
    plugin: Script
    script:
      - cd $SRC_DIR
      - bundle install --path vendor/bundle
      - bundle exec jekyll build --destination=/var/www/html
