language: ruby
sudo: false
rvm: 2.2.0
script: bundle exec rake deploy
env:
  global:
    secure: e026KSabZAPEYNrmKP/bWqhzFPfPbeZb6Xf+v0dreT4TykSCNwtylxT9YHSxmLUZoAwcy4VMp9A4og+M5yRLa435bzVkzTFP5H2yiMzTvYOUou3cBFM8+iFleCOhnAX0fS2e7mvl0yBrYpmf06BYD+0SiYayEMc6p5BYvaRDhb3G+WOyjuHRDf/Yrsd+amaIClwkPBinP6xjL79HO9eUdpy/09YK5G6xHhOuNvRFuf9A3UI3RB8Tyzkrwli1zLEV4wxI6OSD3HMk7Hh51QPo/hd3DNgT1tErLkYhtPofC5dW6pAAAr92ndPra054/8TvA9yPh6tFLNCcjM2QgP7MBYKl4RSkFovFJLjY1d6KgWH55ly7elktzEiTi7kC9zHkCHA9w4mZCDi6YcjSwH+jRcDBS6wyvq31MQ6UcBPC3FSbMovECNhRSuSMtLllUTsNJP3GRH+rmPKPrTlqa8cqNG5QyeyyLiRrBmI3z6gnsBE+ZFETHW8dXA5i3agMyCZ5PTaB8e8D6mH2owqPowGMjry+V1MpFIfxPZlVpbd1+jN6oLgSqAt8C0uLDX8Oa7SMZ8KykfX0wTWlqTtHm+knoCsOOFBVDbqP3ehEO2RvZkhz5uTk/vKcmUxD3Y2l2YnBBqqUzeBv8RRzQTAtn5MO1ro/kImJw4UVnbJt8gF9hRk=
notifications:
  slack:
    secure: Zy2szuaW1lRzQS+5vqCedBKiiYnK7HaffhU869cYIsfiOw27+033wQ67nUX89zI7LZWK+eLJLbe2yBT6qr/vyFXTU3FRXt+Wb5CTmWROQ1MMkj5dvPBcDkz5HOAu6xpzOAcElqFxL/Ptuh1s8WiC0+diIs5xYeus1Y1te1mzpTIVROVB3WmlWSIe2lqZIlGsUiwcCUSBPq+qLvJBCx0MZoBZFlJPmqRt3B9c7ozpf0GI5TCxLQEh/Bog5hFlss4M0MBdFkfd6aczY1AssOKsDMdHkR58pxq/XNWwKNWBGkw6iQ8/HCcbC+p6TCI1UdilgQMg9nhfVO6WG/61bRU2iEiOCvOKpc3GDu0If5M4UIiY5+IIFFK0+oz8hZZfQT1hW4tODNWn1WgCwTH9mx7M+6/jRq3zRxw8xhQzv0TkPP91DRrwVkG2j442WX7Hhr6gQMCAqUd7BkB0/8WBU9O0mMek4TDTXMOJGC9GhMEnL7MlSRGbaDjl904yB+veyWVZELkmQpCCDAnkXNV/H1A2pbNBNrqDmk7B74krZh2v1ypE0n1T6lyVYspctrya0z61r28YzL2WOmKJjTZ52AsT1FGUtRAgE7MYu5ZehdCNUlXrsWglvftZniA/XQvhHfvYO59itj/WD5VPXx8jk3jPFRlt0iUMrQ6FUpVZOYCJ5ks=
branches:
  only:
  - master
