# Site settings
title: Probo
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Probo is a Quality Assurance platform that lets your team test 
  features on your site while in development, helping you get 
  feedback while you’re working.  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://probo.ci" # the base hostname & protocol for your site
twitter_username: zivtech
github_username:  proboci

# Build settings
highlighter: pygments
markdown: kramdown
exclude:
  - 'config.ru'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'vendor'
  - 'package.json'
  - 'node_modules'
  - 'autoprefixer.yml'
  - 'Gruntfile.js'

# Assets pipeline settings
assets:
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/posts
  css_compressor: sass
  js_compressor: uglifier
  cache: true
  cachebust: hard

gems:
- compass
- respond-to
- sass
- uglifier
- compass-normalize
- jekyll-assets
- jekyll-assets/compass