# Site settings
title: Probo.ci
email: info@probo.ci
description: Probo website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://probo.ci"
twitter_username: zivtech
github_username:  proboci
paginate:  5
paginate_path: "/blog/page:num/"

# Build settings
highlighter: pygments
markdown: kramdown
kramdown:
  input: GFM
exclude:
  - 'config.ru'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'vendor'
  - 'package.json'
  - 'node_modules'
  - 'autoprefixer.yml'
  - 'Gruntfile.js'

# Assets pipeline settings
assets:
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/posts
    - _assets/docs
  css_compressor: sass
  js_compressor: uglifier
  cache: true
  cachebust: hard

gems:
- compass
- respond-to
- sass
- uglifier
- font-awesome-sass
- compass-normalize
- jekyll-assets
- jekyll-assets/compass
