source 'https://rubygems.org'
ruby '2.2.0'
gem 'bundler'
gem 'jekyll', '2.4.0'
gem 'rack-jekyll'
gem 'github-pages', '33'
gem 'kramdown'
gem 'jekyll-assets'
gem 'rubyzip'
gem 'sass', '>=3.4'
gem 'uglifier'
gem 'compass', '>1.0'
gem 'respond-to'
gem 'autoprefixer-rails'
gem 'compass-normalize'
gem 'octopress-minify-html'
gem 'breakpoint'